name = climate_zones_biomegen
title = Biome Generator
author = Handmade9485
description = Library providing biomes and decorations for compatible Lua mapgens. Original by Gael de Sailly "https://gitlab.com/gaelysam/biomegen"
min_minetest_version = 5.12
